### ISSUE TITLE
permission error on MacOS

### ISSUE THREAD

**Issue by lilygthb** [pointtonull/anki-external_editor#7]
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.33 (3f403040) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
Platform: Mac 10.14.6
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-09-03 11:56:06
Add-ons possibly involved: ⁨External Editor⁩

Caught exception:
Traceback (most recent call last):
  File "aqt/webview.py", line 493, in handler
  File "aqt/editor.py", line 481, in <lambda>
  File "aqt/editor.py", line 524, in <lambda>
  File "/Users/XX/Library/Application Support/Anki2/addons21/16727059/__init__.py", line 61, in edit_with_external_editor
    text = edit(text)
  File "/Users/XX/Library/Application Support/Anki2/addons21/16727059/__init__.py", line 51, in edit
    proc = subprocess.Popen(cmd_list, close_fds=True)
  File "subprocess.py", line 854, in __init__
  File "subprocess.py", line 1702, in _execute_child
PermissionError: [Errno 13] Permission denied: '/Applications/Atom.app'

**Comment by pointtonull** [comment]
Very interesting.
You have an invalid installation (maybe sudo installed something with root privileges inside a user's path?).
It did not occur to me this could happen. I will add some error handling around this operation.

**Comment by lilygthb** [comment]
>  (maybe sudo installed something with root privileges inside a user's path?).


mmhhh should I be worried? Do you refer to Atom installation or something else?
How can I check if is something malicious??

**Comment by pointtonull** [comment]
No!
Don't be worried. Miss-installations are the wine and bread of MacOSX. I am sorry I did not create the bugfix. I am moving to another country and I've been a bit overwhelmed with work. I'll get to it soon.

**Comment by lilygthb** [comment]
> No!
> Don't be worried. Miss-installations are the wine and bread of MacOSX. I am sorry I did not create the bugfix. I am moving to another country and I've been a bit overwhelmed with work. I'll get to it soon.

Thanks, I was afraid something bad had root privileges..
Good luck with the move!
